# Workflow for building and deploying a Vite project to the gh-pages branch
name: Deploy to GitHub Pages (gh-pages branch)

on:
  # Runs on pushes targeting the `main` branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow pushing to the gh-pages branch
permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Or your preferred LTS version

      - name: Install dependencies
        run: npm install

      - name: Build project
        # The build script in package.json runs `tsc && vite build`
        # Vite automatically builds to the 'dist' directory
        run: npm run build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The directory the action should deploy from.
          publish_dir: ./dist

